version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./marmitas-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000/api
      - VITE_APP_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  # Backend service
  backend:
    build:
      context: ./marmitas-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_POOL_MIN=2
      - DB_POOL_MAX=10
      - DB_POOL_IDLE_TIMEOUT=10000
      # Add database and other backend environment variables here
    restart: unless-stopped
    # Uncomment to add volume for data persistence if needed
    # volumes:
    #  - ./data:/app/data

# Uncomment to define networks if needed for more complex setups
# networks:
#  marmitas-network:
#    driver: bridge 